app/Http/routes.php
<?php
use Illuminate\Support\Facades\Input ;


use App\Stock ;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Session;
use App\Panier ;
use App\Commande;
use ZanySoft\LaravelPDF\PDF;
use Illuminate\Support\Facades\Mail;
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::post('/envoyer', function (Request $request) {

    $data = array('mess' => input::get('message'), 'email' => input::get('email'), 'nom' =>input::get('nom'), 'prenom' =>input::get('prénom'), 'telephone' =>input::get('telephone'));


    Mail::send('email.email', $data, function($message) {
        $message->from('tunisrando@gmail.com', 'Sender Name')->to('tunisrando@gmail.com', 'Receiver Name')->subject('This is the subject');
    });


        return redirect('/contact_us');


});

Route::get('/bb', function() {
    $pdf = PDF::make();
    $pdf->addPage('hello');
    $pdf->send();
});

Route::get('/', function () {
    return view('welcome');
});
Route::get('ajax_produit',function (){
    $date_id = Input::get('date_id');
    $date = Stock::where('id','=',$date_id)->get();
    return Response::json($date);

});


Route::post('ajaxshow', 'FronProduitController@show');

View::composer('welcome', function($view)
{

    $view->with('Blogs', \App\Blogss::all()->take(3));
    $view->with('produits', \App\Produit::all()->take(10));

});
Route::get('error404',[ 'as'=>'notfound','uses'=>'ErrorController@getForm']);

View::composer('layouts.main', function($view)
{
    $view->with('categorie', \App\Category::all()->take(5));
    $view->with('souscategorie', \App\ssCategory::all()->take(4));
    $view->with('menu', \App\menu::all());
    $view->with('detail', \App\Produit::all());
    $view->with('sscategories', \App\ssCategory::all());


    //Si Session panier
    $vieuxPanier = Session::get('panier');
    //On assigne le panier en cours à $panier
    $panier = new Panier($vieuxPanier);
    $view->with('produits', $panier->produits);
    $view->with('prixTotal', $panier->prixTotal);
    $view->with('quantiteTotal', $panier->quantiteTotal);




});

Route::post ( '/Recherche', function () {
$c =Input::get('category_id');
    $q = Input::get ( 'q' );
    $query = $q ;
    if ($c==0)
    $details = \App\Produit::where ( 'Title', 'LIKE', '%' . $q . '%' )->paginate(20);
   else
       $details = \App\Produit::where ( 'Title', 'LIKE', '%' . $q . '%' )->Where ( 'Categorie', '=',  $c  )->paginate(20);

    if (count ( $details ) > 0)

        return view ( 'ProduitRechercher',compact('details','query'));
    else
        return view ( 'ProduitRechercher' )->withMessage ( 'Aucun Produit trouvé. Essayez de rechercher à nouveau!' );
} );


Route::get('/send','SendEmailController@send');



View::composer('shop.panier', function($view)
{
    $view->with('detail', \App\Produit::all());

});
Route::get('grid', 'GridController@getForm');
Route::get('grid/{idss?}',  [
    'uses' => 'GridController@detailssCategorie',
]);
Route::get('detailProduit/{id?}','FrontProduitController@getProduit');


Route::get('creation_compte', 'ContactController@getForm');
Route::post('creation_compte', 'ContactController@postForm');

Route::get('login', 'LoginController@getForm');
Route::post('login', 'LoginController@postForm');

Route::auth();

Route::get('list', 'ListController@getForm');
Route::post('list', 'Listcontroller@postForm');



Route::get('compare', 'CompareController@getForm');
Route::post('compare', 'CompareController@postForm');

Route::get('multiple_addresses', 'Multiple_addressesController@getForm');
Route::post('multiple_addresses', 'Multiple_addressesController@postForm');

Route::get('product_detail', 'Product_detailController@getForm');
Route::post('product_detail', 'Product_detailController@postForm');

Route::get('quick_view', 'Quick_viewController@getForm');
Route::post('quick_view', 'Quick_viewController@postForm');

Route::get('shopping_cart', 'Shopping_cartController@getForm');
Route::post('shopping_cart', 'Shopping_cartController@postForm');

Route::get('forget_password', 'Forget_passwordController@getForm');
Route::post('forget_password', 'Forget_passwordController@postForm');

Route::get('contact_us', 'Contact_usController@getForm');
Route::post('contact_us', 'Contact_usController@postForm');

Route::get('/home', 'HomeController@index');
/*Grid*/


/*Dashboard*/
Route::get('dashboard', 'DashboardController@getForm');
Route::post('dashboard', 'DashboardController@postForm');

/*About_us*/
Route::get('about_us', 'AboutusController@getForm');
Route::post('about_us', 'AboutusController@postForm');

/*Blog*/
Route::get('blog', 'BlogController@getForm');
Route::get('Blog/{id?}', 'BlogController@detailBlog');



/*Chekout*/
Route::get('checkout', 'CheckoutController@getForm');
Route::post('checkout', 'CheckoutController@postForm');

/*Faq*/
Route::get('faq', 'FaqController@getForm');
Route::post('faq', 'FaqController@postForm');

/*Welcome*/
Route::get('welcome', 'IndexController@getForm');
Route::post('welcome', 'IndexController@postForm');

/*Contact_us*/
Route::get('contact_us', 'Contact_usController@getForm');
Route::post('contact_us', 'Contact_usController@postForm');


route::group(['middleware'=>['auth']],function () {

    Route::resource('Profile', 'ProfileController');
    Route::resource('ModifierPassword', 'Auth\ModifierPasswordController');

    route::resource('AjouterProduit', 'FrontAjouteProduitCOntroller');
    route::resource('FrontStock', 'frontStockController');
    Route::resource('ConfirmationFrontProduit', 'confirmationFrontProduitController');
    Route::get('AjouterFrontDate/{id?}', 'AjouterFrontDateController@create');

    Route::resource('AjouterFrontDate', 'AjouterFrontDateController');


    route::resource('Commande', 'FrontCOmmandeController');
    Route::get('facture/{id?}', 'FrontCOmmandeController@facture');




});
route::resource('detailCategorie','FrontssCategorieController');


Route::resource('SendEmail','SendEmailController');

/*backOffice*/


route::get('admin','authadmin\authadminController@showLoginForm');
route::post('Blogin','authadmin\authadminController@login');

route::group(['middleware'=>['admin']],function (){
    route::get('/Bindex','Admin\AdminController@dashboard');
    route::get('/logoutadmin','authadmin\authadminController@logout');
    Route::resource('BBlog','BackBlogController');
    Route::resource('BackCategorie','BackCategorieCOntroller');
    Route::resource('user','BackUserController');
    Route::resource('BProduits','BackProduitController');
    Route::resource('BStock','BackStockController');
    Route::resource('Bprofile','BackProfileController');
    Route::resource('ConfirmationProduit','confirmationProduitController');
    Route::get('AjouterDate/{id?}','AjouterDateController@create');
    Route::get('SupprimerDate/{id?}','AjouterDateController@delete');
    Route::resource('AjouterDate','AjouterDateController');
    Route::resource('ssBackCategorie','ssBackCategorieCOntroller');
    Route::resource('BCommande','BackCommandeController');
    Route::resource('Bmenu','BackMenuController');

    Route::post('BackRechercheMenu','BackMenuController@get_menu_by_recherche');
    Route::post('BackRechercheCategorie','BackCategorieCOntroller@get_Categorie_by_recherche');
    Route::post('BackRecherchessCategorie','ssBackCategorieController@get_ssCategorie_by_recherche');
    Route::post('BackRechercheUtilisateur','BackUserController@get_user_by_recherche');











    route::resource('post','Admin\PostsController');
 
});
route::get('/create',function (){
   App\User::create([
      'name'=>'houssem',
       'lastname'=>'marnissi',
    'role'=>'2',
     'email'=>'admin@admin.com',
        'password'=>bcrypt('09151213'),
   ]);
});
//panier //
Route::post('AjouteProduit',function () {
    $idDate = Input::get ( 'date' );
    $QuantiteSaisie = Input::get ( 'qty' );

    $prixTotaleAvecOption =Input::get ( 'inputPrixTotale' );
   // session_start();
    //$_SESSION['finalPrix']=$prixTotaleAvecOption;4
    session(['finalPrix' => $prixTotaleAvecOption]);
    session(['quantitesaisie' => $QuantiteSaisie]);
    $opt1 = Input::get ( 'Price_1' );
    $opt2 = Input::get ( 'Price_2' );
    $opt3 = Input::get ( 'Price_3' );

    if ($opt1!=null)
        session(['opt1' => $QuantiteSaisie ]);
    else
        session(['opt1' => 0 ]);
if ($opt2!=null)
    session(['opt2' => $QuantiteSaisie ]);
else
    session(['opt2' => 0 ]);
if ($opt3!=null)
    session(['opt3' => $QuantiteSaisie ]);
else
    session(['opt3' => 0 ]);


    return redirect('/ajouter-au-panier/'.$idDate);
}

);
Route::get('/ajouter-au-panier/{id}', [
    'uses' => 'ProduitController@getAjouterAuPanier',
    'as' => 'produit.ajouterAuPanier'
]);
Route::get('/panier', [
    'uses' => 'ProduitController@getPanier',
    'as' => 'produit.panier'
]);
Route::get('/remove-from-cart/{id}', [
    'uses' => 'ProduitController@getRemoveFromCart',
    'as' => 'cart.delete'
]);
Route::get('/paiement', [
    'uses' => 'ProduitController@getPaiement',
    'as' => 'paiement',
    'middleware' => 'auth'
]);
Route::get('/vider-panier', [
    'uses' => 'ProduitController@viderPanier',
    'as' => 'vider.panier'
]);



Route::post('/paiement', [
    'uses' => 'ProduitController@postPaiement',
    'as' => 'paiement',
    'middleware' => 'auth'
]);

Route::get('/acces_non_autorise', function () {
    return view('errors.acces_non_autorise');
})->name('acces_non_autorise');





//Route::group(['middleware' => ['web']], function () {
// //   Route::get('payPremium', ['as'=>'payPremium','uses'=>'PaypalController@payPremium']);

resources/views/CreateStock.blade.php
@extends('layouts.main')
<!-- Main -->
@section('content')



    <div class="main-container col2-right-layout">
        <div class="main container">
            <div class="row">
                <div class="col-main col-sm-9">
                    <div class="page-title">
                        <h2>Ajoute déclinaison</h2>
                    </div>


                        {!! Form::open(array('route'=>'FrontStock.store','name'=>'Form1')) !!}

                        <div class="form-group">
                            {!! Form::label('Date ','Date :') !!}
                            <input type="date" name="Date" class="form-control" style="width: 831px;">
                            @if ($errors->has('Date'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('Date') }}</strong>
                                    </span>
                            @endif
                        </div>
                        <div class="form-group">
                            <input type="hidden" name="idProduit" value="{{$idProduit}}">
                        </div>
                        <div class="form-group">
                            {!! Form::label('Stock','Stock :') !!}
                            <input type="number" name="Stock" class="form-control" style="width: 831px;">

                        @if ($errors->has('Stock'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('Stock') }}</strong>
                                    </span>
                            @endif
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Prix :</label>
                            <div class="col-sm-9">
                                <input type="text" name="Prix0" class="form-control" id="inputCurrency" data-plugin="formatter"
                                       data-pattern="DT[[999]],[[999]].[[99]]"  onKeyUp='CalculerMontantTTC()'/>

                                @if ($errors->has('Prix0'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('Prix0') }}</strong>
                                    </span>
                                @endif
                                <p class="help-block">DT999,999.99</p>
                            </div>

                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Prix avec TVA :</label>
                            <div class="col-sm-9">
                                <input type="number" name="PrixTVA" disabled="true" class="form-control" step="any" id="inputCurrency" data-plugin="formatter"
                                       value="">
                                <p class="help-block">DT999,999.99     &&     TVA = 20% </p>
                            </div>

                        </div>


                    </div>

                </div>

                <!-- Example Wizard Accordion -->
                <div class="col-md-9" >
                    <div class="margin-bottom-30">
                        <div class="panel-group" id="exampleWizardAccordion" aria-multiselectable="true"
                             role="tablist">
                            <div class="panel">
                                <div class="panel-heading" id="exampleHeading1" role="tab">
                                    <a class="panel-title" data-toggle="collapse" href="#exampleCollapse1" data-parent="#exampleWizardAccordion"
                                       aria-expanded="true" aria-controls="exampleCollapse1">
                                        Ajouter  un deuxième prix
                                    </a>
                                </div>
                                <div class="panel-collapse collapse in" id="exampleCollapse1" aria-labelledby="exampleHeading1"
                                     role="tabpanel">
                                    <div class="panel-body">
                                        {!! Form::label('nom','Nom de l\'option n°1 :') !!}
                                        {!! Form::text('Option1',null,['class'=>'maxlength-textarea form-control mb-sm']) !!}
                                        {!! Form::label('Prix','Prix :') !!}

                                        <input type="text" name="Prix1" class="form-control" step="any" id="inputCurrency" data-plugin="formatter"
                                               data-pattern="DT[[999]],[[999]].[[99]]" />
                                        <p class="help-block">DT999,999.99</p>                        </div>
                                    @if ($errors->has('Prix1'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('Prix1') }}</strong>
                                    </span>
                                    @endif
                                </div>
                                <div class="panel">
                                    <div class="panel-heading" id="exampleHeading2" role="tab">
                                        <a class="panel-title collapsed" data-toggle="collapse" href="#exampleCollapse2"
                                           data-parent="#exampleWizardAccordion" aria-expanded="false" aria-controls="exampleCollapse2">
                                            Ajouter un troisieme prix
                                        </a>
                                    </div>
                                    <div class="panel-collapse collapse" id="exampleCollapse2" aria-labelledby="exampleHeading2"
                                         role="tabpanel">
                                        <div class="panel-body">
                                            {!! Form::label('nom','Nom de l\'option n°2 :') !!}
                                            {!! Form::text('Option2',null,['class'=>'maxlength-textarea form-control mb-sm']) !!}

                                            {!! Form::label('Prix','Prix :') !!}

                                            <input type="text" name="Prix2" class="form-control" step="any" id="inputCurrency" data-plugin="formatter"
                                                   data-pattern="DT[[999]],[[999]].[[99]]" />
                                            <p class="help-block">DT999,999.99</p>
                                            @if ($errors->has('Prix2'))
                                                <span class="help-block">
                                        <strong>{{ $errors->first('Prix2') }}</strong>
                                    </span>
                                            @endif
                                        </div>
                                    </div>
                                </div>

                                <div class="panel">
                                    <div class="panel-heading" id="exampleHeading3" role="tab">
                                        <a class="panel-title collapsed" data-toggle="collapse" href="#exampleCollapse3"
                                           data-parent="#exampleWizardAccordion" aria-expanded="false" aria-controls="exampleCollapse3">
                                            Ajouter un quatrième prix                                    </a>
                                    </div>
                                    <div class="panel-collapse collapse" id="exampleCollapse3" aria-labelledby="exampleHeading3"
                                         role="tabpanel">
                                        <div class="panel-body">
                                            {!! Form::label('nom','Nom de l\'option n°3 :') !!}
                                            {!! Form::text('Option3',null,['class'=>'maxlength-textarea form-control mb-sm']) !!}

                                            {!! Form::label('Prix','Prix :') !!}

                                            <input type="text" name="Prix3" class="form-control" step="any" id="inputCurrency" data-plugin="formatter"
                                                   data-pattern="DT[[999]],[[999]].[[99]]" />
                                            <p class="help-block">DT999,999.99</p>
                                            @if ($errors->has('Prix3'))
                                                <span class="help-block">
                                        <strong>{{ $errors->first('Prix3') }}</strong>
                                    </span>
                                            @endif
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- End Example Wizard Accordion -->



                    <div class="form-group">
                        {!! Form::button('Enregistrer',['type'=>'submit','class'=>'button submit','onclick'=>'verification()']) !!}
                    </div>

                </div>
            </div>

            {!! Form::close() !!}

        </div>










    </div>

    <Script language='javascript'>
        function CalculerMontantTTC()
        {
            Form1.PrixTVA.value = Number(Form1.Prix0.value) + Number((Form1.Prix0.value / 100) * 20) ;
        }
    </Script>
    @stop

resources/views/Profile.blade.php
@extends('layouts.main')
<!-- Main -->
@section('content')


    <div class="container target">
        <div class="row">
            <div class="col-sm-10">
                <h1 class=""><spam>Bienvenue sur votre profile, <strong>{{ Auth::user()->lastname }}</strong></spam></h1>


            </div>

                    <div class="col-sm-2"><a  class="pull-right">@if(Auth::user()->file == null)<img title="profile image" class="img-circle img-responsive" src="{{asset('images/profile.png')}}">@else
                                <img title="profile image" class="img-circle img-responsive" src="{{asset(Auth::user()->file)}}">@endif</a>
            </div>

        </div>
        <br>
        <div class="row">
            <div class="col-sm-3">
                <!--left col-->
                <ul class="list-group">
                    <li class="list-group-item text-right" style="background: #af93f6;height: 40px" ><strong style="float: left; color: white">PROFILE</strong></li>
                    <li class="list-group-item text-right"><span class="pull-left"><strong class="">Nom</strong></span> {{ Auth::user()->name }}</li>
                    <li class="list-group-item text-right"><span class="pull-left"><strong class="">Prénom</strong></span> {{ Auth::user()->lastname }}</li>

                    <li class="list-group-item text-right"><span class="pull-left"><strong class="">Date d'inscription</strong></span> {{ Auth::user()->created_at->format('d/m/Y') }}</li>

                    <li class="list-group-item text-right"><span class="pull-left"><strong class="">Email</strong></span> {{ Auth::user()->email }}</li>

                    <li class="list-group-item text-right"><span class="pull-left"><strong class="">Role: </strong></span>
                        <?php if (Auth::user()->role=="1")
                        {
                            echo "Organisateur";
                        }
                        else if (Auth::user()->role=="0")
                        {
                            echo "Client";
                        }else
                            echo "Administrateur";

                        ?></li>
                </ul>
                <div class="panel panel-default">
                    <div class="panel-heading" style="background: #af93f6;height: 40px"><strong style="float: left; color: white">PARAMETRE DU COMPTE</strong>

                    </div>
                    <div class="panel-body"><i style="color:green" class="fa fa-check-square"></i><a href="/ModifierPassword"><b><U>Modifier Mot de passe</U></b></a>

                    </div>
                </div>
            </div>
            <!--/col-3-->
            <div class="col-sm-9 " contenteditable="false" style="">
                <div class="panel panel-default target">
                    <div class="panel-heading" contenteditable="false" style="background: #af93f6;height: 40px"><strong style="float: left; color: white">NOS SERVICES</strong></div>
                    <div class="panel-body" style="height: 296px;">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="thumbnail"style="height: 272px">
                                    <img  src="images/editer.png" height="280" width="185">
                                    <div class="caption">
                                       <center>

                                              <a href="{{route('Profile.edit',[Auth::user()->id])}}">  <button type="submit" title="Submit" class="button submit" > <span> changer </span> </button>
                                            </a>

                                        </center>
                                        <p>
                                            <br>
                                            Changez vos Informations.
                                        </p>
                                        <p>

                                        </p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4 col-sm-7">
                                <div class="thumbnail" style="height: 272px">
                                    <img src="images/commande.jpg" height="280" width="185">
                                    <div class="caption">
                                       <center>
                                            <a href="/Commande">  <button type="submit" title="Submit" class="button submit" > <span> commande </span> </button>
                                            </a>


                                        </center>


                                        <p>
                                            <br>
                                            Affichage de tous vos commandes .
                                        </p>
                                        <p>

                                        </p>
                                    </div>
                                </div>
                            </div>
                            @if(Auth::user()->role=="1" or Auth::user()->role=="2")
                            <div class="col-md-4 col-sm-7">
                                <div class="thumbnail" style="height: 272px">
                                    <img  src="{{asset('images/evenement.png')}}" height="280" width="185">
                                    <div class="caption">

                                        <center>
                                            <a href="{{url('AjouterProduit')}}">  <button type="submit" title="Submit" class="button submit" > <span> évenement </span> </button>
                                            </a>


                                        </center>

                                        <p>
                                        </br>
                                            Ajouter des evenements.
                                        </p>
                                        <p>

                                        </p>
                                    </div>
                                </div>

                            </div>
                                @endif

                        </div>

                    </div>

                </div>



</div>
        </div>


        <!-- End Quantcast tag -->





    </div>
    @stop

resources/views/ajouterProduit.blade.php
@extends('layouts.main')
<!-- Main -->
@section('content')
    <div class="main-container col2-right-layout">
        <div class="main container">
            <div class="row">
                <div class="col-main col-sm-12">
                    <div class="page-title">
                        <h2>vos évenement</h2>
                    </div>
<div style="float: right">
    {{link_to_route('AjouterProduit.create','Ajouter',[Auth::user()->id],['class'=>'buy-btn'])}}
</div>
                </div>


        @if($produit->count())
        <div class="category-products">

            <div class="toolbar">
                <div class="sorter">




                </div>
            </div>
            <ul class="products-grid">
                @foreach($produit as $produits)

                    <li class="item col-lg-3 col-md-5 col-sm-7 col-xs-6">
                        <div class="col-item">
                            <div class="sale-label sale-top-right">
                                {!! Form::open(array('route'=>['AjouterProduit.destroy',$produits->id],'method'=>'DELETE')) !!}
                                <button type="submit" class="btn btn-outline btn-danger"><i class="icon wb-trash" aria-hidden="true"></i></button>

                                {!! Form::close() !!}
                                </div>

                            <div class="product-image-area"> <a class="product-image" title="Afficher Produit" href="{{url('detailProduit/'.$produits->id)}}"> <img src="{{asset($produits->PhotosPrincipale)}}"  alt="a" width="300" height="250"/> </a>
                                <div class="hover_fly"> <a class="exclusive ajax_add_to_cart_button" href="{{route('AjouterProduit.edit',$produits->id)}}" title="Modifier Produit">
                                        <div><span><i class="icon wb-settings" aria-hidden="true"></i>Modifier</span></div>
                                    </a> <a class="quick-view" href="{{url('detailProduit/'.$produits->id)}}">
                                        <div><i class="icon-eye-open"></i><span>Afficher</span></div>

                                    </a> </div>
                            </div>
                            <div class="info">
                                <div class="info-inner">
                                    <div class="item-title"> <a title=" Afficher Produit" href="{{url('detailProduit/'.$produits->id)}}">{{$produits->Title}}</a> </div>
                                    <!--item-title-->
                                    <div class="item-content">

                                        <div class="price-box">
                                            <p class="special-price"> <span class="price"> $45.00 </span> </p>

                                        </div>
                                    </div>
                                    <!--item-content-->
                                </div>
                                <!--info-inner-->

                                <div class="clearfix"> </div>
                            </div>
                        </div>
                    </li>
                @endforeach
            </ul>
                        <div class="toolbar">




                            <div class="pages">


                                <ul class="pagination" style="float: right;">
                                    {{$produit->render()}}
                                </ul>
                            </div>
                        </div>
                </div>

        </div>
    @else
                <div class="category-products">
                    <li class="item col-lg-6 col-md-5 col-sm-7 col-xs-6">

        <h2>vous n'avez aucun évenement</h2>
                    </li>
                </div>
    @endif
                </div>
            </div>
        </div>
    </div>
    <link rel="apple-touch-icon" href="{{asset('../BackOffice/assets/images/apple-touch-icon.png')}}">
    <link rel="shortcut icon" href="{{asset('../BackOffice/assets/images/favicon.ico')}}">
@stop

resources/views/checkout.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Lazzem
 * Date: 01/03/2017
 * Time: 14:25
 */