app/Http/routes.php
    $data = array('mess' => input::get('message'), 'email' => input::get('email'), 'nom' =>input::get('nom'), 'prenom' =>input::get('prénom'), 'telephone' =>input::get('telephone'));


    Mail::send('email.email', $data, function($message) {
        $message->from('tunisrando@gmail.com', 'Sender Name')->to('tunisrando@gmail.com', 'Receiver Name')->subject('This is the subject');
    });


        return redirect('/contact_us');


});

Route::get('/bb', function() {
    $pdf = PDF::make();
    $pdf->addPage('hello');
    $pdf->send();
});

Route::get('/', function () {
    return view('welcome');
});
Route::get('ajax_produit',function (){
    $date_id = Input::get('date_id');
    $date = Stock::where('id','=',$date_id)->get();
    return Response::json($date);

});


Route::post('ajaxshow', 'FronProduitController@show');

View::composer('welcome', function($view)
{

    $view->with('Blogs', \App\Blogss::all()->take(3));
    $view->with('produits', \App\Produit::all()->take(10));

});
Route::get('error404',[ 'as'=>'notfound','uses'=>'ErrorController@getForm']);

View::composer('layouts.main', function($view)
{
    $view->with('categorie', \App\Category::all()->take(5));
    $view->with('souscategorie', \App\ssCategory::all()->take(4));
    $view->with('menu', \App\menu::all());
    $view->with('detail', \App\Produit::all());
    $view->with('sscategories', \App\ssCategory::all());


    //Si Session panier
    $vieuxPanier = Session::get('panier');
    //On assigne le panier en cours à $panier
    $panier = new Panier($vieuxPanier);
    $view->with('produits', $panier->produits);
    $view->with('prixTotal', $panier->prixTotal);
    $view->with('quantiteTotal', $panier->quantiteTotal);




});

Route::post ( '/Recherche', function () {
$c =Input::get('category_id');
    $q = Input::get ( 'q' );
    $query = $q ;
    if ($c==0)
    $details = \App\Produit::where ( 'Title', 'LIKE', '%' . $q . '%' )->paginate(20);
   else
       $details = \App\Produit::where ( 'Title', 'LIKE', '%' . $q . '%' )->Where ( 'Categorie', '=',  $c  )->paginate(20);

    if (count ( $details ) > 0)

        return view ( 'ProduitRechercher',compact('details','query'));
    else
        return view ( 'ProduitRechercher' )->withMessage ( 'Aucun Produit trouvé. Essayez de rechercher à nouveau!' );
} );


Route::get('/send','SendEmailController@send');



View::composer('shop.panier', function($view)
{
    $view->with('detail', \App\Produit::all());

});
Route::get('grid', 'GridController@getForm');
Route::get('grid/{idss?}',  [
    'uses' => 'GridController@detailssCategorie',
]);
Route::get('detailProduit/{id?}','FrontProduitController@getProduit');


Route::get('creation_compte', 'ContactController@getForm');
Route::post('creation_compte', 'ContactController@postForm');

Route::get('login', 'LoginController@getForm');
Route::post('login', 'LoginController@postForm');

Route::auth();

Route::get('list', 'ListController@getForm');
Route::post('list', 'Listcontroller@postForm');



Route::get('compare', 'CompareController@getForm');
Route::post('compare', 'CompareController@postForm');

Route::get('multiple_addresses', 'Multiple_addressesController@getForm');
Route::post('multiple_addresses', 'Multiple_addressesController@postForm');

Route::get('product_detail', 'Product_detailController@getForm');
Route::post('product_detail', 'Product_detailController@postForm');

Route::get('quick_view', 'Quick_viewController@getForm');
Route::post('quick_view', 'Quick_viewController@postForm');

Route::get('shopping_cart', 'Shopping_cartController@getForm');
Route::post('shopping_cart', 'Shopping_cartController@postForm');

Route::get('forget_password', 'Forget_passwordController@getForm');
Route::post('forget_password', 'Forget_passwordController@postForm');

Route::get('contact_us', 'Contact_usController@getForm');
Route::post('contact_us', 'Contact_usController@postForm');

Route::get('/home', 'HomeController@index');
/*Grid*/


/*Dashboard*/
Route::get('dashboard', 'DashboardController@getForm');
Route::post('dashboard', 'DashboardController@postForm');

/*About_us*/
Route::get('about_us', 'AboutusController@getForm');
Route::post('about_us', 'AboutusController@postForm');

/*Blog*/
Route::get('blog', 'BlogController@getForm');
Route::get('Blog/{id?}', 'BlogController@detailBlog');



/*Chekout*/
Route::get('checkout', 'CheckoutController@getForm');
Route::post('checkout', 'CheckoutController@postForm');

/*Faq*/
Route::get('faq', 'FaqController@getForm');
Route::post('faq', 'FaqController@postForm');

/*Welcome*/
Route::get('welcome', 'IndexController@getForm');
Route::post('welcome', 'IndexController@postForm');

/*Contact_us*/
Route::get('contact_us', 'Contact_usController@getForm');
Route::post('contact_us', 'Contact_usController@postForm');


route::group(['middleware'=>['auth']],function () {

    Route::resource('Profile', 'ProfileController');
    Route::resource('ModifierPassword', 'Auth\ModifierPasswordController');

    route::resource('AjouterProduit', 'FrontAjouteProduitCOntroller');
    route::resource('FrontStock', 'frontStockController');
    Route::resource('ConfirmationFrontProduit', 'confirmationFrontProduitController');
    Route::get('AjouterFrontDate/{id?}', 'AjouterFrontDateController@create');

    Route::resource('AjouterFrontDate', 'AjouterFrontDateController');


    route::resource('Commande', 'FrontCOmmandeController');
    Route::get('facture/{id?}', 'FrontCOmmandeController@facture');




});
route::resource('detailCategorie','FrontssCategorieController');


Route::resource('SendEmail','SendEmailController');

/*backOffice*/


route::get('admin','authadmin\authadminController@showLoginForm');
route::post('Blogin','authadmin\authadminController@login');

route::group(['middleware'=>['admin']],function (){
    route::get('/Bindex','Admin\AdminController@dashboard');
    route::get('/logoutadmin','authadmin\authadminController@logout');
    Route::resource('BBlog','BackBlogController');
    Route::resource('BackCategorie','BackCategorieCOntroller');
    Route::resource('user','BackUserController');
    Route::resource('BProduits','BackProduitController');
    Route::resource('BStock','BackStockController');
    Route::resource('Bprofile','BackProfileController');
    Route::resource('ConfirmationProduit','confirmationProduitController');
    Route::get('AjouterDate/{id?}','AjouterDateController@create');
    Route::get('SupprimerDate/{id?}','AjouterDateController@delete');
    Route::resource('AjouterDate','AjouterDateController');
    Route::resource('ssBackCategorie','ssBackCategorieCOntroller');
    Route::resource('BCommande','BackCommandeController');
    Route::resource('Bmenu','BackMenuController');

    Route::post('BackRechercheMenu','BackMenuController@get_menu_by_recherche');
    Route::post('BackRechercheCategorie','BackCategorieCOntroller@get_Categorie_by_recherche');
    Route::post('BackRecherchessCategorie','ssBackCategorieController@get_ssCategorie_by_recherche');
    Route::post('BackRechercheUtilisateur','BackUserController@get_user_by_recherche');











    route::resource('post','Admin\PostsController');
 
});
route::get('/create',function (){
   App\User::create([
      'name'=>'houssem',
       'lastname'=>'marnissi',
    'role'=>'2',
     'email'=>'admin@admin.com',
        'password'=>bcrypt('09151213'),
   ]);
});
//panier //
Route::post('AjouteProduit',function () {
    $idDate = Input::get ( 'date' );
    $QuantiteSaisie = Input::get ( 'qty' );

    $prixTotaleAvecOption =Input::get ( 'inputPrixTotale' );
   // session_start();
    //$_SESSION['finalPrix']=$prixTotaleAvecOption;4
    session(['finalPrix' => $prixTotaleAvecOption]);
    session(['quantitesaisie' => $QuantiteSaisie]);
    $opt1 = Input::get ( 'Price_1' );
    $opt2 = Input::get ( 'Price_2' );
    $opt3 = Input::get ( 'Price_3' );

    if ($opt1!=null)
        session(['opt1' => $QuantiteSaisie ]);
    else
        session(['opt1' => 0 ]);
if ($opt2!=null)
    session(['opt2' => $QuantiteSaisie ]);
else
    session(['opt2' => 0 ]);
if ($opt3!=null)
    session(['opt3' => $QuantiteSaisie ]);
else
    session(['opt3' => 0 ]);


    return redirect('/ajouter-au-panier/'.$idDate);
}

);
Route::get('/ajouter-au-panier/{id}', [
    'uses' => 'ProduitController@getAjouterAuPanier',
    'as' => 'produit.ajouterAuPanier'
]);
Route::get('/panier', [
    'uses' => 'ProduitController@getPanier',
    'as' => 'produit.panier'
]);
Route::get('/remove-from-cart/{id}', [
    'uses' => 'ProduitController@getRemoveFromCart',
    'as' => 'cart.delete'
]);
Route::get('/paiement', [
    'uses' => 'ProduitController@getPaiement',
    'as' => 'paiement',
    'middleware' => 'auth'
]);
Route::get('/vider-panier', [
    'uses' => 'ProduitController@viderPanier',
    'as' => 'vider.panier'
]);



Route::post('/paiement', [
    'uses' => 'ProduitController@postPaiement',
    'as' => 'paiement',
    'middleware' => 'auth'
]);

Route::get('/acces_non_autorise', function () {
    return view('errors.acces_non_autorise');
})->name('acces_non_autorise');





//Route::group(['middleware' => ['web']], function () {
// //   Route::get('payPremium', ['as'=>'payPremium','uses'=>'PaypalController@payPremium']);
    //Route::post('getCheckout', ['as'=>'getCheckout','uses'=>'PaypalController@getCheckout']);
    //Route::get('getDone', ['as'=>'getDone','uses'=>'PaypalController@getDone']);
    //Route::get('getCancel', ['as'=>'getCancel','uses'=>'PaypalController@getCancel']);
//});




//Route::post('payment', array(
   // 'as' => 'payment',
  //  'uses' => 'IndexController@postPayment',
//));
// this is after make the payment, PayPal redirect back to your site
//Route::get('payment/status', array(
    //'as' => 'payment.status',
    //'uses' => 'IndexController@getPaymentStatus',
//));
Route::get('paywithpaypal', array('as' => 'addmoney.paywithpaypal','uses' => 'AddMoneyController@payWithPaypal',));

resources/views/BackOffice/BackProduits.blade.php
@extends('layouts.backmain')
@section('content')
  <div class="page animsition">
    <div class="page-content">
      <!-- Panel Basic -->
      @if (Session::has('message'))
        <div class="'alert alert-success">{{Session::get('message')}}</div>
      @endif


      <div class="panel">
        <header class="panel-heading">
          <div class="panel-actions"></div>
          <h3 class="panel-title">Les produits</h3>
        </header>

        <div class="panel-body">
          <table class="table table-hover dataTable table-striped width-full" data-plugin="dataTable">

            <thead>
            <tr>
                <th>Titre</th>
              <th>Sous Categorie</th>
              <th>Organisateur</th>
              <th>Quantité</th>
              <th>Date</th>
              <th>Action</th>
            </tr>
            </thead>
            <tfoot>
            <tr>
              <th>Titre</th>
              <th>Sous Categorie</th>
              <th>Organisateur</th>
              <th>Quantité</th>
              <th>Date</th>
              <th>Action</th>
            </tr>


            </tfoot>
            <tbody>





                @foreach ($resultat as $resultat)
                  <input type="hidden" value="{{$id++}}">
                  <tr>
                      <td>{{$resultat->Title}}</td>

                      <td> @foreach ($sscategory as $sscateg)
                              @if($sscateg->id == $resultat->Categorie)
                                  {{$sscateg->title}}
                               @endif
                               @endforeach
                      </td>
                <td>{{$resultat->Organisateur}}</td>
             <td>{{$resultat->Stock}}</td>
                      <td>{{$resultat->Date}}</td>

                      <td>
                          <table>
                              <tr>
                  <td><button class="btn btn-outline btn-primary" data-target="#exampleTabs{{$id}}" data-toggle="modal"
                          type="button"><i class="icon wb-eye" aria-hidden="true"></i> </button></td>
                <td>
                    <a href="{{route('BProduits.edit',$resultat->idProduit)}}"> <button type="button" class="btn btn-outline btn-success"><i class="icon wb-settings" aria-hidden="true"></i></button>
                    </a>
                </td>

                <td>{!! Form::open(array('route'=>['BProduits.destroy',$resultat->idProduit],'method'=>'DELETE')) !!}
                          <button type="submit" class="btn btn-outline btn-danger"><i class="icon wb-trash" aria-hidden="true"></i></button>

                {!! Form::close() !!}</td></tr></table>

              <!-- Modal -->
              <div class="modal fade" id="exampleTabs{{$id}}" aria-hidden="true" aria-labelledby="exampleModalTabs"
                   role="dialog" tabindex="-1">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header"    style="margin-left:50px;" >
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                      </button>
                        <table>
                            <tr><td><h3>Titre :</h3><h4 class="modal-title" id="exampleModalTabs">{{$resultat->Title}}</h4>

                           <td>        </td> </td><td colspan="3"><img src="{{$resultat->PhotosPrincipale}}" width="200" height="100"></td></tr></table>
                    </div>


                      <div class="">
                        <div class="" style="margin: 57px"id="exampleLine1" role="tabpanel">
                            <h3>Description principale :</h3>
                          {{$resultat->DescriptionMineur}}
                            <h3>Deuxième description</h3>
                            {{$resultat->Description}}


                        </div>

                        <div class=""style="margin: 57px" id="exampleLine2" role="tabpanel">
                          <h4> Date : {{$resultat->Date}}</h4>
                            <h4> Stock : {{$resultat->Stock}}</h4>
                            <h4> Status : @if ($resultat->Status ==0)
                            Activer
                            @else Désactiver @endif</h4>
                            <h4>Prix Intitial:{{$resultat->Prix0}} </h4>



                        </div>

                        <div class="" style="margin: 57px" id="exampleLine3" role="tabpanel">
                            <img src="{{$resultat->Photos1}}" width="50" height="50">
                            <img src="{{$resultat->Photos2}}" width="50" height="50">

                        </div>
                      </div>

                  </div>
                </div>
              </div>
              <!-- End Modal -->
                      </td>
                  </tr>
            @endforeach

            </tbody>
          </table>
        </div>
      </div>
      <!-- End Panel Basic -->
    </div>
  </div>


  <script>
      (function(document, window, $) {
          'use strict';

          var Site = window.Site;

          $(document).ready(function($) {
              Site.run();
          });

          // Fixed Header Example
          // --------------------
          (function() {
              // initialize datatable
              var table = $('#exampleFixedHeader').DataTable({
                  responsive: true,
                  "bPaginate": false,
                  "sDom": "t" // just show table, no other controls
              });

              // initialize FixedHeader
              var offsetTop = 0;
              if ($('.site-navbar').length > 0) {
                  offsetTop = $('.site-navbar').eq(0).innerHeight();
              }
              var fixedHeader = new FixedHeader(table, {
                  offsetTop: offsetTop
              });

              // redraw fixedHeaders as necessary
              $(window).resize(function() {
                  fixedHeader._fnUpdateClones(true);
                  fixedHeader._fnUpdatePositions();
              });
          })();

          // Individual column searching
          // ---------------------------
          (function() {
              $(document).ready(function() {
                  var defaults = $.components.getDefaults("dataTable");

                  var options = $.extend(true, {}, defaults, {
                      initComplete: function() {
                          this.api().columns().every(function() {
                              var column = this;
                              var select = $(
                                  '<select class="form-control width-full"><option value=""></option></select>'
                              )
                                  .appendTo($(column.footer()).empty())
                                  .on('change', function() {
                                      var val = $.fn.dataTable.util.escapeRegex(
                                          $(this).val()
                                      );

                                      column
                                          .search(val ? '^' + val + '$' : '',
                                              true, false)
                                          .draw();
                                  });

                              column.data().unique().sort().each(function(
                                  d, j) {
                                  select.append('<option value="' + d +
                                      '">' + d + '</option>')
                              });
                          });
                      }
                  });

                  $('#exampleTableSearch').DataTable(options);
              });
          })();

          // Table Tools
          // -----------
          (function() {
              $(document).ready(function() {
                  var defaults = $.components.getDefaults("dataTable");

                  var options = $.extend(true, {}, defaults, {
                      "aoColumnDefs": [{
                          'bSortable': false,
                          'aTargets': [-1]
                      }],
                      "iDisplayLength": 5,
                      "aLengthMenu": [
                          [5, 10, 25, 50, -1],
                          [5, 10, 25, 50, "All"]
                      ],
                      "sDom": '<"dt-panelmenu clearfix"Tfr>t<"dt-panelfooter clearfix"ip>',
                      "oTableTools": {
                          "sSwfPath": "../../assets/vendor/datatables-tabletools/swf/copy_csv_xls_pdf.swf"
                      }
                  });

                  $('#exampleTableTools').dataTable(options);
              });
          })();

          // Table Add Row
          // -------------

          (function() {
              $(document).ready(function() {
                  var defaults = $.components.getDefaults("dataTable");

                  var t = $('#exampleTableAdd').DataTable(defaults);

                  $('#exampleTableAddBtn').on('click', function() {
                      t.row.add([
                          'Adam Doe',
                          'New Row',
                          'New Row',
                          '30',
                          '2015/10/15',
                          '$20000'
                      ]).draw();
                  });
              });
          })();
      })(document, window, jQuery);
  </script>

  {{link_to_route('BProduits.create','Ajout',null,['class'=>'site-action btn-raised btn btn-success btn-floating'])}}

@stop

resources/views/BackOffice/RecherchessCategorie.blade.php
@extends('layouts.Backmain')
@section('content')
    <div class="page animsition">
        <div class="page-header">
            <h1 class="page-title">Sous Categories </h1>
            <div class="page-header-actions">
                <form action="/BackRecherchessCategorie" method="POST" role="search">
                    {{ csrf_field() }}
                    <div class="input-search input-search-dark">
                        <i class="input-search-icon wb-search" aria-hidden="true"></i>
                        <input type="text" class="form-control" name="q" placeholder="Recherche...">
                    </div>
                </form>
            </div>
        </div>
        @if(isset($details))
            <div class="page-content">
                <div class="projects-wrap">
                    <ul class="blocks blocks-100 blocks-xlg-5 blocks-md-4 blocks-sm-3 blocks-xs-2">

                        <p> Les résultats de la recherche pour  <b> {{ $query }} </b> sont :</p>

                        @foreach($details as $Categories)

                            <li>
                                <div class="panel">
                                    <figure class="overlay overlay-hover animation-hover">
                                        <img class="caption-figure" src="{{asset($Categories->file)}}" height="140" width="170">
                                        <figcaption class="overlay-panel overlay-background overlay-fade text-center vertical-align">
                                            <div class="btn-group">

                                                {{link_to_route('BackCategorie.edit','Edit',[$Categories->id],['class'=>'btn btn-icon btn-pure btn-default'])}}

                                                {!! Form::open(array('route'=>['BackCategorie.destroy',$Categories->id],'method'=>'DELETE')) !!}
                                                {!! Form::button('Delete',['type'=>'submit','class'=>'btn btn-icon btn-pure btn-default']) !!}
                                                {!! Form::close() !!}
                                            </div>
                                            {{link_to_route('BackCategorie.show','Afficher',[$Categories->id],['class'=>'btn btn-outline btn-default project-button'])}}

                                        </figcaption>
                                    </figure>
                                    <div class="time pull-right">{{$Categories->created_at}}</div>
                                    <div>{{str_limit($Categories->title, $limit = 10, $end = '..')}}</div>
                                </div>
                            </li>

                        @endforeach

                    </ul>
                </div>


                <nav>
                    <ul class="pagination pagination-no-border">
                        {{$details->render()}}

                    </ul>
                </nav>

            </div>
        @elseif(isset($message))
            <p>{{ $message }}</p>
        @endif

    </div>


    <!--add project form -->
    {{link_to_route('ssBackCategorie.create','Add',null,['class'=>'site-action btn-raised btn btn-success btn-floating'])}}


    </div>
    </div>
    </div>

@stop

resources/views/BackOffice/createBackCategorie.blade.php
@extends('layouts.Backmain')
@section('content')
    <div class="page animsition">
        <div class="page-header">
            <h1 class="page-title">Ajouter categorie </h1>

        </div>
        <div class="page-content">
            <div class="projects-wrap">


                 <div class="modal-body">

                    {!! Form::open(['url'=>'/BackCategorie', 'method'=>'POST', 'files'=>'true']) !!}

                     <div class="form-group">
                         <label for="userfile">Image File</label>
                         <input type="file" class="form-control" name="userfile">
                     </div>

                     <div class="form-group">
                         <label for="title">Title</label>
                         <input type="text" class="form-control" name="title" value="">
                     </div>
                     <div class="form-group">
                         <div class="form-group ">
                             <label for="select">Affichage sur le menu</label>

                             <select class="form-control" name="idmenu" value=idmenu>
                                 <option value="">Aucun </option>
                                 @foreach($menu as $menus)

                                     <option value="{{$menus->id}}" >{{$menus->title}}</option>

                                 @endforeach
                             </select>

                         </div>
                     </div>


                     <div class="form-group">
                         <label for="description">Description</label>
                         <textarea class="form-control" name="description"></textarea>
                     </div>

                     <div class="form-group">
                         <button type="submit" class="btn btn-primary">Upload</button>
                         <a href="{{ url('/BackCategorie') }}" class="btn btn-warning">Cancel</a>
                     </div>


                    {!! Form::close() !!}
                 </div>

                @if($errors->has())
                    <div class="alert alert-danger">
                        @foreach($errors->all() as $error)
                            <p>{{ $error }}</p>
                        @endforeach
                    </div>
                @endif

            </div>
        </div>
    </div>












@stop

resources/views/BackOffice/createssBackCategorie.blade.php
@extends('layouts.Backmain')
@section('content')
    <div class="page animsition">
        <div class="page-header">
            <h1 class="page-title">Sous-Categorie</h1>
            <div class="page-header-actions">
                <form>
                    <div class="input-search input-search-dark">
                        <i class="input-search-icon wb-search" aria-hidden="true"></i>
                        <input type="text" class="form-control" name="" placeholder="Search...">
                    </div>
                </form>
            </div>
        </div>
        <div class="page-content">
            <div class="projects-wrap">


                 <div class="modal-body">

                    {!! Form::open(['route'=>'ssBackCategorie.store', 'method'=>'POST', 'files'=>'true']) !!}

                     <div class="form-group">
                         <label for="userfile">Image</label>
                         <input type="file" class="form-control" name="userfile">
                     </div>

                     <div class="form-group">
                         <select class="form-control" name="tag_id" value="tag_id">
                             @foreach($categorie as $Categories)

                                 <option value="{{$Categories->id}}" >{{$Categories->title}}</option>

                             @endforeach
                         </select>
                     </div>

                     <div class="form-group">
                         <label for="title">Title</label>
                         <input type="text" class="form-control" name="title">
                     </div>

                     <div class="form-group">
                         <label for="description">Description</label>
                         <textarea class="form-control" name="description"></textarea>
                     </div>

                     <div class="form-group">
                         <button type="submit" class="btn btn-primary">Upload</button>
                         <a href="{{ url('/ssBackCategorie') }}" class="btn btn-warning">Cancel</a>
                     </div>

                    {!! Form::close() !!}

                 </div>

                @if($errors->has())
                    <div class="alert alert-danger">
                        @foreach($errors->all() as $error)
                            <p>{{ $error }}</p>
                        @endforeach
                    </div>
                @endif

            </div>
        </div>
    </div>
@stop

resources/views/BackOffice/detailUser.blade.php
@extends('layouts.Backmain')
@section('content')
    <div class="page animsition">
        <div class="page-header">
            <h1 class="page-title">Afficher</h1>
            <div class="page-header-actions">

            </div>
        </div>
        <div class="page-content">
            <div class="projects-wrap">


                 <div class="modal-body">

                    {!! Form::model($User,array('route'=>array('user.show',$User->id),'method'=>'GET')) !!}

                     <div class="form-group">
                         {!! Form::label('Nom','Nom ') !!}
                         {!! Form::text('name',null,['class'=>'form-control','disabled'=>'true']) !!}
                     </div>

                     <div class="form-group">
                         {!! Form::label('Prénom','Prenom ') !!}
                         {!! Form::text('lastname',null,['class'=>'form-control','disabled'=>'true']) !!}
                     </div>

                     <div class="form-group">
                         <select class="form-control" name="role" value="role" disabled="true">
                             @if($User->role==0)
                                 <option value="0" selected="true" >Client</option>
                                 <option value="1" >Organisateur</option>
                                 <option value="2" >Administrateur</option>
                             @endif
                             @if($User->role==1)
                                 <option value="0" >Client</option>
                                 <option value="1" selected="true" >Organisateur</option>
                                 <option value="2"  >Administrateur</option>
                             @endif
                             @if($User->role==2)
                                 <option value="0" >Client</option>
                                 <option value="1" >Organisateur</option>
                                 <option value="2" selected="true" >Administrateur</option>
                             @endif
                         </select>
                     </div>

                     <div class="form-group">
                         {!! Form::label('e-mail','E-mail ') !!}
                         {!! Form::text('email',null,array('class'=>'form-control','disabled'=>'true')) !!}
                     </div>



                    {!! Form::close() !!}

                     <div class="form-group">
                         <a href="/user"><button class="btn btn-primary" type="button"><span>Retour</span></button></a>
                     </div>
                 </div>

            </div>
        </div>
    </div>












@stop